replicaCount: 1

image:
  pullPolicy: Always
  repository: myorgregistry.azurecr.io/documind-ollama
  tag: latest # override in CD pipeline.

fullnameOverride: "documind-ollama-ms"

env:
  GIN_MODE: "release"
  OLLAMA_KEEP_ALIVE: "16h"
# ingress:
#   annotations:
#     appgw.ingress.kubernetes.io/connection-draining: "true"
#     appgw.ingress.kubernetes.io/connection-draining-timeout: "30"
#     # appgw.ingress.kubernetes.io/rewrite-rule-set: security-response-headers
#     appgw.ingress.kubernetes.io/ssl-redirect: "true"
#     cert-manager.io/cluster-issuer: letsencrypt
#     kubernetes.io/ingress.class: azure/application-gateway

app:
  port: 11434

service:
  port: 11434

livenessProbe:
  enabled: false

readinessProbe:
  enabled: false

resources:
  requests:
    memory: 8Gi
    cpu: 1.5
  limits:
    memory: 12Gi
    cpu: 1.5

tolerations:
  - key: dedicated
    operator: Equal
    value: documind
    effect: NoSchedule

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: agentpool
              operator: In
              values:
                - documind