name: Deploy to Sbox

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Container Image Tag to deploy"
        required: true  
      
      namespace:
        type: choice
        required: true
        description: 'Namespace where to deploy to'
        options:
          - documind
          - dev

jobs:
  deploy-to-sbox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - ocr
          - ollama
    env:
      GITHUB_TOKEN: ${{ secrets.BOT_GH_TOKEN }}
      ACR_REGISTRY: myorgregistry.azurecr.io
      RESOURCE_GROUP: "documind-aks-rg"
      CLUSTER_NAME: "documind-aks-cluster"
      HELM_CHART_VERSION: "0.7.8"
      
    steps:
      - id: Clone_Repository
        uses: actions/checkout@v2
      - run: git fetch --unshallow --tags

      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: Azure/get-keyvault-secrets@v1
        id: get_secrets
        with:
          keyvault: "myorg-gh-actions"
          secrets: "ACR-LOGINSERVER, ACR-PASSWORD, ACR-USERNAME, AZURE-SUBSCRIPTION-ID"

      - uses: Azure/docker-login@v1
        with:
          login-server: ${{ steps.get_secrets.outputs.ACR-LOGINSERVER }}
          username: ${{ steps.get_secrets.outputs.ACR-USERNAME }}
          password: ${{ steps.get_secrets.outputs.ACR-PASSWORD }}

      - name: Kube Auth
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}

      - name: Helm Deployment
        run: |
          # Get helm parameters
          APP=${{  matrix.service  }}
          SBOX=$(echo ${{ github.event.inputs.namespace }} | awk -F'-' '{print $1}')
          PATH_TO_HELM_VALUES_ENVIRONMENT="helm/${SBOX}-sbox/defaults.yaml"
          HELM_CHART_VERSION=${{ env.HELM_CHART_VERSION }}
          ImageTag=${{ github.event.inputs.tag }}

          cd $APP

          # Helm deploy OCR
          helm pull oci://${ACR_REGISTRY}/helm-charts/microservice --version $HELM_CHART_VERSION
          helm upgrade documind-$APP oci://${ACR_REGISTRY}/helm-charts/microservice --install --version $HELM_CHART_VERSION --namespace $SBOX --values helm/defaults.yaml,$PATH_TO_HELM_VALUES_ENVIRONMENT --set image.tag=$ImageTag --debug --wait
